# Generated by Django 6.0.5 on 2026-05-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
