# Generated by Django 6.0.5 on 2026-05-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_tenant_plan_platformadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stripe_account_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
